### ISSUE TITLE
Problems with translations in 1room -家出少女-

### ISSUE THREAD

**Issue by ManlyMarco** [XUnity-Development/XUnity.AutoTranslator#4]
I tried to use AutoTranslator in that game, and it works well in menus, but it breaks parts of the in-game UI and soft-locks the dialogue. Below is a piece of the generated tl file:
> <size=28>Day</size>20<size=28>(木)</size>=<size = 28> Day </ size> 20 <size = 28> (Thursday) </ size>
> <size=28>Day</size>20<size=28>(木)</size>=<size = 28> Day </ size> 20 <size = 28> (Thursday) </ size>

Every time I run the game it generates a new identical entry. The spaces inside and outside <> tags cause UI problems, because they are no longer seen as tags.
![capture](https://user-images.githubusercontent.com/39247311/43679017-f256f6b6-981d-11e8-92ec-da789cdb0e98.JPG)

Another issue is that the VN textbox seems to be failing to load (which causes the game to soft-lock) whenever AutoTranslator is lodaded. Nothing shows up in log, even with all Debug flags enabled. This happens with EnableUGUI=True, the game uses only this.

**Comment by Scrublord1336** [comment]
I'll check it out.

**Comment by ManlyMarco** [comment]
In case anyone wants to run AutoTranslator with this game - Use BepInEx v4.1 x86 and after starting the game once edit config.ini and set 'entrypoint-assembly=UnityEngine.CoreModule.dll'

**Comment by Scrublord1336** [comment]
You can also just use the ReiPatcher version.

Anyway. This game is based on [Utage](https://assetstore.unity.com/packages/templates/systems/utage-unity-text-adventure-game-engine-15905).

Many of the classes in that Engine extend from the UGUI "Text" class, which is why it "works", but not really.

Another problem, that you did not mention, is that the things that actually are translated properly are cutoff to the length of the kana that was translated. ^_^

I might need some help in figuring out how I should hook into this Engine properly, as I have tried to do so before, and failed miserably.

You can decompile the source with dotPeek, which also makes the code nice and readable.

The classes I am currently looking at are:

AdvGuiMessageWindow, UguiNovelText, UguiNovelTextGenerator, AdvPage, AdvEngine.

If you enable the option in the config file and press ALT+Y it will print out the GameObject hierarchy with associated components to a file called hierarchy.txt in the game root.

At least you can do all this, if you are interested in helping me. :)

Do you know if there are better tools available to "debug" unity games and their gameobject hierarchies?

**Comment by ManlyMarco** [comment]
@Scrublord1336 You can debug with [dnSpy](https://github.com/0xd4d/dnSpy/wiki/Debugging-Unity-Games). The correct mono.dll is in Unity-debugging-win32.zip

**Comment by Scrublord1336** [comment]
The reason it generates two entries with the same string is because it uses the equal sign in the text key.

**Comment by ManlyMarco** [comment]
Maybe split these strings into parts then? If there's a = or a <> tag then take all nearby non-Japanese characters and split.
For example this:
<size=28>Day20</size><size=28>(木)</size>
Becomes Day20 and (木)

**Comment by Scrublord1336** [comment]
Something like that would unquestionably be needed in order to handle any text containing syntax. Such syntax should never go through the translator endpoint. It will always be mangled.

**Comment by Scrublord1336** [comment]
Then again, using a syntax where you can't use an equal sign seems weak as hell as well.

**Comment by ManlyMarco** [comment]
Escape the = and only split on tags then?

**Comment by Scrublord1336** [comment]
I have some ideas that I will try out.

On another note, I was looking at the game engine and I think I might have found something interesting:

AdvCommand.cs
```C#
    public string ParseCellLocalizedText()
    {
      string currentLanguage = AdvColumnName.Text.QuickToString();
      if ((Object) LanguageManagerBase.Instance != (Object) null && this.RowData.Grid.ContainsColumn(LanguageManagerBase.Instance.CurrentLanguage))
        currentLanguage = LanguageManagerBase.Instance.CurrentLanguage;
      if (this.RowData.IsEmptyCell(currentLanguage))
        return this.RowData.ParseCellOptional<string>(AdvColumnName.Text.QuickToString(), string.Empty);
      return this.RowData.ParseCellOptional<string>(currentLanguage, string.Empty);
    }
```

I am pretty sure this method returns all text that can be localized. The only problem is that it cannot be hooked in an async manner. I'll see if it actually does what I suspect.

**Comment by Scrublord1336** [comment]
Hah. Can confirm a hook on this method works flawlessly. Only problem is things wont be translated first time you see them.

Two options:
 * Make request SYNCHRONOUSLY on the game loop thread. My heart cries just thinking about this.
 * See if there is some way to reload text after it has been loaded once.

**Comment by ManlyMarco** [comment]
Confirmed fixed
